#!/bin/bash

CLOJUREC_HOME=$(pwd)/lib/clojurec
CLJC_REPL_HOME=$(pwd)
CLJC_REPL_TMP=.repl
CLJC_REPL_COLORS=true
CLJC_REPL_DBUS=$( [[ $OSTYPE =~ ^darwin ]] && echo false || echo true )

CP=
for jar in $CLOJUREC_HOME/src/clj $CLJC_REPL_HOME/src/clj $CLJC_REPL_HOME/lib/* ; do
  CP=$CP:$jar
done

mkdir -p $CLJC_REPL_TMP
( cd $CLJC_REPL_TMP && find . -mindepth 1 -maxdepth 1 ! -iname cache -exec rm -rf {} \; )
mkdir -p $CLJC_REPL_TMP/cache
mkdir -p $CLJC_REPL_TMP/eval

export CLOJUREC_HOME CLJC_REPL_HOME CLJC_REPL_COLORS CLJC_REPL_DBUS
export LD_LIBRARY_PATH=$CLJC_REPL_TMP:$LD_LIBRARY_PATH

( cd $CLJC_REPL_TMP && java -server -cp $CP -Djna.nosys=true clojure.main -e "
(require '[cljc.repl :as repl])
(repl/repl)
" )
